[package]
name = "storage-file" # или gpp_storage
version = "0.1.0"
edition = "2021"

[dependencies]
gpp_core = { path = "../core" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"